version: 0.2
phases: 
  install:
    runtime-versions:
        java: corretto17
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo Logging in to Amazon ECR....
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}-${CODEBUILD_BUILD_NUMBER}
      - REPOSITORY_URI=513661464973.dkr.ecr.us-east-1.amazonaws.com/ecr-docker-image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 513661464973.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - echo pushing  docker Image to ECR repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - cd $CODEBUILD_SRC_DIR
  post_build: 
    commands: 
      - echo Writing image definitions file for service refresh...
      - printf '[{"name":"test-container","imageUri":"%s"}]'  $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
 
